Review
yana-pavlova/stellar-burgers pull request #1
Opened 2024-07-21 08:56 UTC by yana-pavlova

2024-07-21 10:24 UTC, SergeyK2004 requested changes
Здравствуйте. (Нужно развернуть общий комментарий ↓)
Посмотрите на гитхабе все комментарии к коду

Работа проделана огромная
Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно, хорошо выполнена работа с хранилищем и работа с асинхронными запросами. Защищеные роут работают в соответствии с условием задания.
Что нужно исправить:

* https://disk.yandex.ru/d/EM-RCpifOISjPg Если ингредиент добавлен в конструктор, то в каталоге должно отображаться количество добавленных ингредиентов. Сверьтесь с макетом.
* Нужно центрировать контент на странице с деталями ингредиента, скрин https://disk.yandex.ru/d/f-Utvgs2P3pshg 
* import { useDispatch, useSelector } from 'react-redux'; такого больше не должно быть в проекте. Хуки useDispatch, useSelector нужно типизировать 1 раз в отдельном файле и заменить их во всем проекте на свои, а не из библиотеки react-redux . Вот ссылка на документацию по их типизации https://redux.js.org/usage/usage-with-typescript#define-typed-hooks
* protectedRoute.tsx нужно убрать в components, так как это компонент

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.
Комментарии Можно лучше не обязательны к исправлению прямо сейчас, это рекомендации
Удачного рефакторинга кода.

2024-07-21 10:24 UTC, SergeyK2004 commented on src/components/burger-ingredient/burger-ingredient.tsx
> +import { useDispatch } from 'react-redux';
**Надо исправить:**

Хуки useDispatch, useSelector нужно брать из файла `src/services/store.ts` Они там уже типизированы

2024-07-21 10:24 UTC, SergeyK2004 commented on src/components/burger-ingredient/burger-ingredient.tsx
> +        id: nanoid() // генерация уникального айди, чтобы в бургере могли быть одинаковые ингредиенты
**Отлично:**

Хорошо, что id генерируется за проеделами редьюсера

2024-07-21 10:24 UTC, SergeyK2004 commented on src/components/ProtectedRoute.tsx
> +export const ProtectedRoute = ({
**Надо сиправить:**

Файл нужно перенести в папку с компонентами, так как это тоже компонент.

2024-07-21 19:24 UTC, SergeyK2004 approved these changes
Отличная работа. Поздравляю со сдачей проекта.

2024-07-22 04:02 UTC, yana-pavlova commented
Спасибо за ревью!

2024-07-22 04:03 UTC, merged